version: "3.3"
   
services:
  db:
    image: mariadb:10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    build: .
    command: python3 main.py
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
      - celery
      - celery-beat
      - db
      
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app.celery:app worker  --loglevel=info
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app.celery:app beat  --loglevel=info
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --bind 0.0.0.0

volumes:
  mariadb_data:
